### ISSUE TITLE
请问博客不能评论吗

### ISSUE THREAD

**Issue by chrisyy2003** [Squirre17/Squirre17.github.io#1]
不嫌弃的话，师傅加个友链吧
name: chrisyy
link: https://blog.chrisyy.top
avatar: https://blog.chrisyy.top/imgs/avatar.png
descr: blockchain//Move/Solidity/Minecraft

**Comment by Squirre17** [comment]
已加友链，我可能只在文章那边开了评论，改天改改其他页面🥰

**Comment by chrisyy2003** [comment]
> 已加友链，我可能只在文章那边开了评论，改天改改其他页面🥰

好的，那师傅也发下信息吧

**Comment by Squirre17** [comment]
name: Squirre17
link: https://squirre17.github.io/
avatar: https://squirre17.github.io/imgs/avatar.jpg
descr: Binary Security/Blockchain Rookie
